"""Shared country names for customer storage and English PI documents."""
COUNTRIES = {'Afghanistan': '阿富汗', 'Albania': '阿尔巴尼亚', 'Algeria': '阿尔及利亚', 'Angola': '安哥拉', 'Argentina': '阿根廷', 'Armenia': '亚美尼亚', 'Australia': '澳大利亚', 'Austria': '奥地利', 'Azerbaijan': '阿塞拜疆', 'Bahrain': '巴林', 'Bangladesh': '孟加拉国', 'Belarus': '白俄罗斯', 'Belgium': '比利时', 'Benin': '贝宁', 'Bolivia': '玻利维亚', 'Brazil': '巴西', 'Bulgaria': '保加利亚', 'Cambodia': '柬埔寨', 'Cameroon': '喀麦隆', 'Canada': '加拿大', 'Chile': '智利', 'China': '中国', 'Colombia': '哥伦比亚', 'Costa Rica': '哥斯达黎加', 'Croatia': '克罗地亚', 'Cuba': '古巴', 'Czech Republic': '捷克', 'Denmark': '丹麦', 'Ecuador': '厄瓜多尔', 'Egypt': '埃及', 'Estonia': '爱沙尼亚', 'Ethiopia': '埃塞俄比亚', 'Finland': '芬兰', 'France': '法国', 'Georgia': '格鲁吉亚', 'Germany': '德国', 'Ghana': '加纳', 'Greece': '希腊', 'Guatemala': '危地马拉', 'Honduras': '洪都拉斯', 'Hong Kong': '中国香港', 'Hungary': '匈牙利', 'Iceland': '冰岛', 'India': '印度', 'Indonesia': '印度尼西亚', 'Iran': '伊朗', 'Iraq': '伊拉克', 'Ireland': '爱尔兰', 'Israel': '以色列', 'Italy': '意大利', 'Japan': '日本', 'Jordan': '约旦', 'Kazakhstan': '哈萨克斯坦', 'Kenya': '肯尼亚', 'Kuwait': '科威特', 'Kyrgyzstan': '吉尔吉斯斯坦', 'Laos': '老挝', 'Latvia': '拉脱维亚', 'Lebanon': '黎巴嫩', 'Libya': '利比亚', 'Lithuania': '立陶宛', 'Luxembourg': '卢森堡', 'Malaysia': '马来西亚', 'Maldives': '马尔代夫', 'Mexico': '墨西哥', 'Mongolia': '蒙古', 'Morocco': '摩洛哥', 'Myanmar': '缅甸', 'Nepal': '尼泊尔', 'Netherlands': '荷兰', 'New Zealand': '新西兰', 'Nigeria': '尼日利亚', 'North Korea': '朝鲜', 'Norway': '挪威', 'Oman': '阿曼', 'Pakistan': '巴基斯坦', 'Panama': '巴拿马', 'Peru': '秘鲁', 'Philippines': '菲律宾', 'Poland': '波兰', 'Portugal': '葡萄牙', 'Qatar': '卡塔尔', 'Romania': '罗马尼亚', 'Russia': '俄罗斯', 'Saudi Arabia': '沙特阿拉伯', 'Serbia': '塞尔维亚', 'Singapore': '新加坡', 'Slovakia': '斯洛伐克', 'Slovenia': '斯洛文尼亚', 'South Africa': '南非', 'South Korea': '韩国', 'Spain': '西班牙', 'Sri Lanka': '斯里兰卡', 'Sweden': '瑞典', 'Switzerland': '瑞士', 'Syria': '叙利亚', 'Taiwan': '中国台湾', 'Tajikistan': '塔吉克斯坦', 'Tanzania': '坦桑尼亚', 'Thailand': '泰国', 'Tunisia': '突尼斯', 'Turkey': '土耳其', 'Turkmenistan': '土库曼斯坦', 'UAE': '阿联酋', 'Uganda': '乌干达', 'Ukraine': '乌克兰', 'United Kingdom': '英国', 'United States': '美国', 'Uruguay': '乌拉圭', 'Uzbekistan': '乌兹别克斯坦', 'Venezuela': '委内瑞拉', 'Vietnam': '越南', 'Yemen': '也门', 'Chad': '乍得', 'Guinea': '几内亚', 'Republic of the Congo': '刚果（布）', 'Democratic Republic of the Congo': '刚果（金）', 'Gabon': '加蓬', 'Botswana': '博茨瓦纳', 'Rwanda': '卢旺达', 'Saint Lucia': '圣卢西亚', 'Dominican Republic': '多米尼加共和国', 'Micronesia': '密克罗尼西亚联邦', 'Palestine': '巴勒斯坦', 'Paraguay': '巴拉圭', 'Burkina Faso': '布基纳法索', 'Cayman Islands': '开曼群岛', 'Moldova': '摩尔多瓦', 'Fiji': '斐济', 'New Caledonia': '新喀里多尼亚', 'Mauritius': '毛里求斯', 'French Polynesia': '法属波利尼西亚', 'Puerto Rico': '波多黎各', 'Bosnia and Herzegovina': '波黑', 'Jamaica': '牙买加', 'Reunion': '留尼汪', 'Ivory Coast': '科特迪瓦', 'Kosovo': '科索沃', 'American Samoa': '美属萨摩亚', 'Sudan': '苏丹', 'Suriname': '苏里南', 'Mozambique': '莫桑比克', 'El Salvador': '萨尔瓦多', 'North Macedonia': '北马其顿', 'Malta': '马耳他', 'Mali': '马里', 'Zambia': '赞比亚', 'Togo': '多哥'}
ALIASES = {'UAE': '阿联酋', 'USA': '美国', 'US': '美国', 'UK': '英国', '印尼': '印度尼西亚', '孟加拉': '孟加拉国', '蒙古国': '蒙古', '斐济群岛': '斐济', '马其顿': '北马其顿', 'Türkiye': '土耳其'}
_LOOKUP = {name.casefold(): zh for en, zh in COUNTRIES.items() for name in (en, zh)}
_LOOKUP.update({key.casefold(): value for key, value in ALIASES.items()})
_ENGLISH = {zh: en for en, zh in COUNTRIES.items()}
def normalize_country(value):
    value = str(value or '').strip()
    return _LOOKUP.get(value.casefold(), value)
def english_country(value):
    return _ENGLISH.get(normalize_country(value), str(value or '').strip())
